name: Build Mod

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile.mod"
      - "custom-cont-init.d/**"
      - ".github/workflows/build-mod.yaml"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Create VARS
        id: vars
        run: |
          echo "commit=${GITHUB_REF//refs\/heads\//}" >> $GITHUB_OUTPUT
          echo "tag=$(echo ${GITHUB_REPOSITORY//docker-/} | tr '[:upper:]' '[:lower:]'):mod" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: roxedus
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.6.1
        with:
          push: true
          provenance: false # https://github.com/docker/buildx/issues/1509
          file: Dockerfile.mod
          tags: |
            ghcr.io/${{ steps.vars.outputs.tag }}
            ghcr.io/${{ steps.vars.outputs.tag }}-${{ github.sha }}
