name: Build Image

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile"
      - "root/**"
      - ".github/workflows/build-image.yaml"
  schedule:
    - cron: "0 20 1,15 * 5"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        architecture: [linux-arm64, linux-amd64]
    outputs:
      time: ${{ steps.vars.outputs.time }}
      upstream: ${{ steps.vars.outputs.upstream }}

    steps:
      - uses: actions/checkout@v4
      - name: Create VARS
        id: vars
        run: |
          ARCHITECTURE=${{ matrix.architecture }}
          MITMPROXY_RELEASE=$(curl -sX GET https://api.github.com/repos/mitmproxy/mitmproxy/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]' | sed 's|^v||')
          echo "platform=${ARCHITECTURE//-/\/}" >> $GITHUB_OUTPUT
          echo "repo=$(echo ${GITHUB_REPOSITORY//docker-/} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "time=$(date --utc +%Y-%m-%d_%H.%M)" >> $GITHUB_OUTPUT
          echo "source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/tree/${GITHUB_REF//refs\/heads\//}" >> $GITHUB_OUTPUT
          echo "url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/blob/master/README.md" >> $GITHUB_OUTPUT
          echo "tag=$(echo ${GITHUB_REPOSITORY//docker-/} | tr '[:upper:]' '[:lower:]'):${MITMPROXY_RELEASE}-${{ matrix.architecture }}" >> $GITHUB_OUTPUT
          echo "upstream=${MITMPROXY_RELEASE}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.5.0
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master #v0.10.5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: roxedus
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.3.0
        with:
          push: true
          attests: type=sbom,generator=docker/buildkit-syft-scanner
          #sbom: true
          provenance: true # https://github.com/docker/buildx/issues/1509
          platforms: ${{ steps.vars.outputs.platform }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            ghcr.io/${{ steps.vars.outputs.tag }}
          build-args: MITMPROXY_RELEASE=${{ steps.vars.outputs.upstream }}
          labels: |
            org.opencontainers.image.created=${{ steps.vars.outputs.time }}
            org.opencontainers.image.title=${{ steps.vars.outputs.repo }}
            org.opencontainers.image.source=${{ steps.vars.outputs.source }}
            org.opencontainers.image.url=${{ steps.vars.outputs.url }}

  publish:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: roxedus
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifests for GitHub Container Registry
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          IMAGE=ghcr.io/$(echo ${GITHUB_REPOSITORY//docker-/} | tr '[:upper:]' '[:lower:]')
          TAG=${{ needs.build.outputs.upstream }}
          SOURCE=${IMAGE}:${TAG}
          docker buildx imagetools create -t ${IMAGE}:${{ needs.build.outputs.time }}     ${SOURCE}-linux-amd64 ${SOURCE}-linux-arm64
          docker buildx imagetools create -t ${IMAGE}:${{ needs.build.outputs.upstream }} ${SOURCE}-linux-amd64 ${SOURCE}-linux-arm64
          if [[ ${GITHUB_REF//refs\/heads\//} == main ]]; then
          docker buildx imagetools create -t ${IMAGE}:latest                              ${SOURCE}-linux-amd64 ${SOURCE}-linux-arm64
          fi
